# Generated by Django 5.2.5 on 2025-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.TextField(blank=True, help_text='Enter title with line breaks using Enter key', null=True),
        ),
    ]
