# Generated by Django 5.2.5 on 2025-08-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_slider_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slider',
            unique_together={('order',)},
        ),
    ]
