# Generated by Django 5.2.5 on 2025-08-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_slider_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slider',
            unique_together=set(),
        ),
    ]
