# Generated by Django 5.2.5 on 2025-11-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_avatar_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='address_name',
            field=models.CharField(blank=True, help_text="Name/label for this address (e.g., 'Home', 'Work', 'Office')", max_length=100, null=True),
        ),
    ]
